name: Renovate Trigger

on:
  issues:
    types: [edited]
  workflow_dispatch:

concurrency:
  group: renovate-trigger
  cancel-in-progress: true

jobs:
  renovate:
    if: github.event_name != 'issues' || github.event.issue.number == 14
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Run Renovate on Dashboard Action
        run: |
          npx --yes --package renovate renovate \
            --token="${{ secrets.GITHUB_TOKEN }}" \
            --platform=github \
            "${{ github.repository }}"
