name: Renovate (Self-Hosted Runner)

on:
  workflow_dispatch:
  # 1. Автоматический запуск при любом мерже в main
  push:
    branches:
      - main
  # 2. Автоматический запуск при закрытии или мерже любого PR
  pull_request:
    types: [closed]
  # 3. Фоновый запуск по расписанию
  schedule:
    - cron: '0 */2 * * *'

concurrency:
  group: renovate-self-hosted
  cancel-in-progress: false

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Self-Hosted Renovate Run
        uses: renovatebot/github-action@v41.0.14
        with:
          configurationFile: renovate.json5
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: '["${{ github.repository }}"]'
          LOG_LEVEL: 'info'
